### ISSUE TITLE
Hardening: double check the submitted file id is actually a backup before deleting it

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-report_allbackups#2]
Once the file IDs are submitted, there is no double check that they are actually MBZ backup files.

The condition

```
"f.filename like '%.mbz' and f.filename <> '.' and f.component <> 'tool_recyclebin' and f.filearea <> 'draft'"
```

is checked only when populating the table. But whatever IDs are submitted, those files are simply deleted. This represents a small theoretical yet potential surface for data-loss attack.

It might be safer to double check that every file identified by the submitted id, is really a backup file before deleting it.

**Comment by danmarsden** [comment]
Yeah good point - I'll add something in thanks!
